version: "3.9"

services:
  # NextJS
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - ./frontend/:/usr/src/app/

    command: bash -c "npm run dev"

    stdin_open: true
    tty: true
