version: "3.9"

services:
  # NextJS
  frontend:
    environment:
      - NODE_ENV=${NODE_ENV}

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - ./frontend/:/usr/src/app/

    command: bash -c "npm run dev"

    stdin_open: true
    tty: true

  backend:
    environment:
      - NODE_ENV=${NODE_ENV}

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./backend:/usr/src/app

    ports:
      - 8080:8080

    command: bash -c "npm run start:dev"

    stdin_open: true
    tty: true

#   db:
#     platform: linux/x86_64
#     image: mysql:5.7
#     environment:
#       MYSQL_DATABASE: ${DATABASE_NAME}
#       MYSQL_USER: ${DATABASE_USER}
#       MYSQL_PASSWORD: ${DATABASE_PASSWORD}
#       MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#     ports:
#       - "${DATABASE_PORT}:3306"
#     volumes:
#       - ./docker/db/data:/var/lib/mysql
#       - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
# volumes:
#   db-store:
